'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'am' | 'or';

const translations = {
  en: {
    home: 'HOME',
    aboutUs: 'ABOUT US',
    faq: 'FAQ',
    pricing: 'PRICING',
    tutorials: 'TUTORIALS',
    register: 'REGISTER',
    signIn: 'SIGN IN',
    heroTitle: 'Welcome to Ethiopia\'s Premier Auction Platform',
    heroSubtitle: 'Discover unique items, place bids, and win incredible deals on everything from electronics to vehicles.',
    searchPlaceholder: 'Search for auctions...',
    searchButton: 'Search',
    electronics: 'Electronics',
    vehicles: 'Vehicles',
    jewelry: 'Jewelry',
    homeGarden: 'Home & Garden',
    secureBidding: 'Secure Bidding',
    secureBiddingDesc: 'Your bids are protected with enterprise-level security',
    instantUpdates: 'Instant Updates',
    instantUpdatesDesc: 'Get real-time notifications on your auction activity',
    bestDeals: 'Best Deals',
    bestDealsDesc: 'Find incredible deals on premium items every day',
    verifiedSellers: 'Verified Sellers',
    verifiedSellersDesc: 'All sellers are verified for your peace of mind',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    confirmPassword: 'Confirm Password',
    login: 'Login',
    createAccount: 'Create Account',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: 'Don\'t have an account?',
    alreadyHaveAccount: 'Already have an account?',
    dashboard: 'Dashboard',
    myBids: 'My Bids',
    myAuctions: 'My Auctions',
    watchlist: 'Watchlist',
    messages: 'Messages',
    settings: 'Settings',
    logout: 'Logout',
    createAuction: 'Create Auction',
    browseAuctions: 'Browse Auctions',
    currentBid: 'Current Bid',
    timeLeft: 'Time Left',
    placeBid: 'Place Bid',
    buyNow: 'Buy Now',
    addToWatchlist: 'Add to Watchlist',
    bidHistory: 'Bid History',
    description: 'Description',
    seller: 'Seller',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    language: 'Language',
    // About page
    ourMission: 'Our Mission',
    ourStory: 'Our Story',
    transparency: 'Transparency',
    quality: 'Quality',
    community: 'Community',
    trust: 'Trust',
    happyUsers: 'Happy Users',
    itemsSold: 'Items Sold',
    rating: 'Rating',
    // Registration and verification
    verifyAccount: 'Verify Your Account',
    verificationCodeSent: 'We sent a 6-digit code to',
    enterVerificationCode: 'Enter Verification Code',
    verifyingAccount: 'Verifying...',
    didntReceiveCode: "Didn't receive the code?",
    resendOTP: 'Resend OTP',
    sending: 'Sending...',
    // Subscription
    accountVerified: 'Account Verified!',
    activateSubscription: 'Now let\'s activate your subscription',
    selectPaymentMethod: 'Select Payment Method',
    payWithTelebirr: 'Pay with Telebirr mobile money',
    payWithChapa: 'Pay with Chapa payment gateway',
    payWithCBEBirr: 'Pay with Commercial Bank of Ethiopia',
    processing: 'Processing...',
    activateFreeAccount: 'Activate Free Account',
    proceedToPayment: 'Proceed to Payment',
    upgradeAnytime: 'You can upgrade to a paid plan anytime from your dashboard',
    // Auctions
    liveAuctions: 'Live Auctions',
    browseActiveAuctions: 'Browse active auctions and place your bids',
    searchAuctions: 'Search auctions...',
    allCategories: 'All Categories',
    endsIn: 'Ends in',
    bids: 'Bids',
    noAuctionsFound: 'No auctions found matching your criteria',
    // Checkout
    checkout: 'Checkout',
    congratulations: 'Congratulations! You won this auction',
    shippingAddress: 'Shipping Address',
    streetAddress: 'Street Address',
    city: 'City',
    region: 'Region',
    paymentMethod: 'Payment Method',
    orderSummary: 'Order Summary',
    soldBy: 'Sold by',
    winningBid: 'Winning Bid',
    shipping: 'Shipping',
    free: 'Free',
    total: 'Total',
    completePayment: 'Complete Payment',
    paymentSecure: 'Your payment information is secure and encrypted',
    // Auto-bid
    autoBid: 'Auto-Bid',
    autoBidDescription: 'Let the system bid for you automatically up to your maximum amount',
    maxAutoBidAmount: 'Maximum auto-bid amount',
    setAutoBid: 'Set Auto-Bid',
    // Create Auction
    createNewAuction: 'Create New Auction',
    listYourItem: 'List your item and start receiving bids',
    basicInformation: 'Basic Information',
    auctionTitle: 'Title',
    itemCondition: 'Condition',
    conditionNew: 'New',
    conditionLikeNew: 'Like New',
    conditionGood: 'Good',
    conditionFair: 'Fair',
    conditionPoor: 'Poor',
    pricingSection: 'Pricing',
    startingPrice: 'Starting Price',
    reservePrice: 'Reserve Price',
    minimumPriceToSell: 'Minimum price to sell',
    buyNowPrice: 'Buy Now Price',
    optionalInstantBuy: 'Optional instant buy price',
    auctionSettings: 'Auction Settings',
    auctionDuration: 'Auction Duration',
    shippingCost: 'Shipping Cost',
    enterZeroForFree: 'Enter 0 for free shipping',
    imagesSection: 'Images',
    uploadImages: 'Upload Images',
    uploadUpTo10: 'Upload up to 10 images. First image will be the main image.',
    commissionInfo: 'Commission',
    willBeDeducted: 'will be deducted from the final sale price',
    creatingAuction: 'Creating...',
    // Admin
    adminDashboard: 'Admin Dashboard',
    managePlatform: 'Manage users, auctions, and monitor platform activity',
    totalUsers: 'Total Users',
    totalActiveAuctions: 'Active Auctions',
    fraudAlerts: 'Fraud Alerts',
    revenueLabel: 'Revenue',
    userManagement: 'User Management',
    searchUsers: 'Search users...',
    auctionManagement: 'Auction Management',
    searchAuctionsAdmin: 'Search auctions...',
    fraudDetectionAlerts: 'Fraud Detection Alerts',
    transactionManagement: 'Transaction Management',
    blockUser: 'Block',
    viewDetails: 'View',
    flaggedItem: 'Flagged',
    resolveAlert: 'Resolve',
    investigateAlert: 'Investigate',
    detailsLink: 'Details'
  },
  am: {
    home: 'መነሻ',
    aboutUs: 'ስለ እኛ',
    faq: 'ጥያቄዎች',
    pricing: 'ዋጋ',
    tutorials: 'ትምህርቶች',
    register: 'ይመዝገቡ',
    signIn: 'ይግቡ',
    heroTitle: 'እንኳን ወደ ኢትዮጵያ ቀዳሚ የጨረታ መድረክ በደህና መጡ',
    heroSubtitle: 'ልዩ ዕቃዎችን ያግኙ፣ ጨረታ ያድርጉ እና ከኤሌክትሮኒክስ እስከ ተሽከርካሪዎች ድረስ በሁሉም ነገር ላይ አስደናቂ ስምምነቶችን ያሸንፉ።',
    searchPlaceholder: 'ጨረታዎችን ይፈልጉ...',
    searchButton: 'ፈልግ',
    electronics: 'ኤሌክትሮኒክስ',
    vehicles: 'ተሽከርካሪዎች',
    jewelry: 'ጌጣጌጥ',
    homeGarden: 'ቤት እና የአትክልት ቦታ',
    secureBidding: 'ደህንነቱ የተጠበቀ ጨረታ',
    secureBiddingDesc: 'ጨረታዎችዎ በድርጅት ደረጃ ደህንነት የተጠበቁ ናቸው',
    instantUpdates: 'ፈጣን ማሻሻያዎች',
    instantUpdatesDesc: 'በጨረታ እንቅስቃሴዎ ላይ የእውነተኛ ጊዜ ማሳወቂያዎችን ያግኙ',
    bestDeals: 'ምርጥ ስምምነቶች',
    bestDealsDesc: 'በየቀኑ በፕሪሚየም እቃዎች ላይ አስደናቂ ስምምነቶችን ያግኙ',
    verifiedSellers: 'የተረጋገጡ ሻጮች',
    verifiedSellersDesc: 'ሁሉም ሻጮች ለእርስዎ የአእምሮ ሰላም የተረጋገጡ ናቸው',
    email: 'ኢሜይል',
    password: 'የይለፍ ቃል',
    fullName: 'ሙሉ ስም',
    phoneNumber: 'ስልክ ቁጥር',
    confirmPassword: 'የይለፍ ቃል ያረጋግጡ',
    login: 'ግባ',
    createAccount: 'መለያ ፍጠር',
    forgotPassword: 'የይለፍ ቃል ረሱ?',
    dontHaveAccount: 'መለያ የለዎትም?',
    alreadyHaveAccount: 'መለያ አለዎት?',
    dashboard: 'ዳሽቦርድ',
    myBids: 'የእኔ ጨረታዎች',
    myAuctions: 'የእኔ ጨረታዎች',
    watchlist: 'የክትትል ዝርዝር',
    messages: 'መልዕክቶች',
    settings: 'ቅንብሮች',
    logout: 'ውጣ',
    createAuction: 'ጨረታ ፍጠር',
    browseAuctions: 'ጨረታዎችን አስስ',
    currentBid: 'የአሁኑ ጨረታ',
    timeLeft: 'የቀረው ጊዜ',
    placeBid: 'ጨረታ አድርግ',
    buyNow: 'አሁን ግዛ',
    addToWatchlist: 'ወደ ክትትል ዝርዝር አክል',
    bidHistory: 'የጨረታ ታሪክ',
    description: 'መግለጫ',
    seller: 'ሻጭ',
    loading: 'በመጫን ላይ...',
    save: 'አስቀምጥ',
    cancel: 'ሰርዝ',
    delete: 'ሰርዝ',
    edit: 'አርትዕ',
    view: 'ይመልከቱ',
    language: 'ቋንቋ',
    // About page
    ourMission: 'የእኛ ተልዕኮ',
    ourStory: 'የእኛ ታሪክ',
    transparency: 'ግልጽነት',
    quality: 'ጥራት',
    community: 'ማህበረሰብ',
    trust: 'እምነት',
    happyUsers: 'ደስተኛ ተጠቃሚዎች',
    itemsSold: 'የተሸጡ እቃዎች',
    rating: 'ደረጃ',
    // Registration and verification
    verifyAccount: 'መለያዎን ያረጋግጡ',
    verificationCodeSent: '6-አሃዝ ኮድ ወደ ላክንልዎታል',
    enterVerificationCode: 'የማረጋገጫ ኮድ ያስገቡ',
    verifyingAccount: 'በማረጋገጥ ላይ...',
    didntReceiveCode: 'ኮዱን አልተቀበሉም?',
    resendOTP: 'OTP እንደገና ላክ',
    sending: 'በመላክ ላይ...',
    // Subscription
    accountVerified: 'መለያ ተረጋግጧል!',
    activateSubscription: 'አሁን የእርስዎን ምዝገባ እናግብር',
    selectPaymentMethod: 'የክፍያ ዘዴ ይምረጡ',
    payWithTelebirr: 'በቴሌብር ሞባይል ገንዘብ ይክፈሉ',
    payWithChapa: 'በቻፓ የክፍያ መግቢያ ይክፈሉ',
    payWithCBEBirr: 'በኢትዮጵያ ንግድ ባንክ ይክፈሉ',
    processing: 'በማስኬድ ላይ...',
    activateFreeAccount: 'ነጻ መለያ አግብር',
    proceedToPayment: 'ወደ ክፍያ ይቀጥሉ',
    upgradeAnytime: 'በማንኛውም ጊዜ ከዳሽቦርድዎ ወደ የተከፈለ እቅድ ማሻሻል ይችላሉ',
    // Auctions
    liveAuctions: 'የቀጥታ ጨረታዎች',
    browseActiveAuctions: 'ንቁ ጨረታዎችን ያስሱ እና ጨረታዎን ያድርጉ',
    searchAuctions: 'ጨረታዎችን ይፈልጉ...',
    allCategories: 'ሁሉም ምድቦች',
    endsIn: 'ያበቃል በ',
    bids: 'ጨረታዎች',
    noAuctionsFound: 'ከመስፈርትዎ ጋር የሚዛመድ ጨረታ አልተገኘም',
    // Checkout
    checkout: 'ክፍያ',
    congratulations: 'እንኳን ደስ አለዎት! ይህን ጨረታ አሸንፈዋል',
    shippingAddress: 'የማጓጓዣ አድራሻ',
    streetAddress: 'የመንገድ አድራሻ',
    city: 'ከተማ',
    region: 'ክልል',
    paymentMethod: 'የክፍያ ዘዴ',
    orderSummary: 'የትዕዛዝ ማጠቃለያ',
    soldBy: 'የተሸጠው በ',
    winningBid: 'አሸናፊ ጨረታ',
    shipping: 'ማጓጓዣ',
    free: 'ነጻ',
    total: 'ጠቅላላ',
    completePayment: 'ክፍያ አጠናቅቅ',
    paymentSecure: 'የክፍያ መረጃዎ ደህንነቱ የተጠበቀ እና የተመሰጠረ ነው',
    // Auto-bid
    autoBid: 'ራስ-ሰር ጨረታ',
    autoBidDescription: 'ስርዓቱ እስከ ከፍተኛ መጠንዎ ድረስ በራስዎ ምትክ በራስ-ሰር ጨረታ እንዲያደርግ ያድርጉ',
    maxAutoBidAmount: 'ከፍተኛ ራስ-ሰር ጨረታ መጠን',
    setAutoBid: 'ራስ-ሰር ጨረታ አዘጋጅ',
    // Create Auction
    createNewAuction: 'አዲስ ጨረታ ፍጠር',
    listYourItem: 'እቃዎን ዘርዝር እና ጨረታዎችን መቀበል ይጀምሩ',
    basicInformation: 'መሰረታዊ መረጃ',
    auctionTitle: 'ርዕስ',
    itemCondition: 'ሁኔታ',
    conditionNew: 'አዲስ',
    conditionLikeNew: 'እንደ አዲስ',
    conditionGood: 'ጥሩ',
    conditionFair: 'መካከለኛ',
    conditionPoor: 'ደካማ',
    pricingSection: 'ዋጋ አወጣጥ',
    startingPrice: 'መነሻ ዋጋ',
    reservePrice: 'የተጠበቀ ዋጋ',
    minimumPriceToSell: 'ለመሸጥ ዝቅተኛ ዋጋ',
    buyNowPrice: 'አሁን ግዛ ዋጋ',
    optionalInstantBuy: 'አማራጭ ፈጣን ግዢ ዋጋ',
    auctionSettings: 'የጨረታ ቅንብሮች',
    auctionDuration: 'የጨረታ ጊዜ',
    shippingCost: 'የማጓጓዣ ወጪ',
    enterZeroForFree: 'ለነጻ ማጓጓዣ 0 ያስገቡ',
    imagesSection: 'ምስሎች',
    uploadImages: 'ምስሎችን ይስቀሉ',
    uploadUpTo10: 'እስከ 10 ምስሎች ይስቀሉ። የመጀመሪያው ምስል ዋናው ምስል ይሆናል።',
    commissionInfo: 'ኮሚሽን',
    willBeDeducted: 'ከመጨረሻው የሽያጭ ዋጋ ይቀነሳል',
    creatingAuction: 'በመፍጠር ላይ...',
    // Admin
    adminDashboard: 'የአስተዳዳሪ ዳሽቦርድ',
    managePlatform: 'ተጠቃሚዎችን፣ ጨረታዎችን ያስተዳድሩ እና የመድረክ እንቅስቃሴን ይከታተሉ',
    totalUsers: 'ጠቅላላ ተጠቃሚዎች',
    totalActiveAuctions: 'ንቁ ጨረታዎች',
    fraudAlerts: 'የማጭበርበር ማንቂያዎች',
    revenueLabel: 'ገቢ',
    userManagement: 'የተጠቃሚ አስተዳደር',
    searchUsers: 'ተጠቃሚዎችን ይፈልጉ...',
    auctionManagement: 'የጨረታ አስተዳደር',
    searchAuctionsAdmin: 'ጨረታዎችን ይፈልጉ...',
    fraudDetectionAlerts: 'የማጭበርበር ማወቂያ ማንቂያዎች',
    transactionManagement: 'የግብይት አስተዳደር',
    blockUser: 'አግድ',
    viewDetails: 'ይመልከቱ',
    flaggedItem: 'ተሰይሟል',
    resolveAlert: 'አፍታ',
    investigateAlert: 'ይመርምሩ',
    detailsLink: 'ዝርዝሮች'
  },
  or: {
    home: 'MANA',
    aboutUs: 'WAAʼEE KEENYA',
    faq: 'GAAFFII',
    pricing: 'GATII',
    tutorials: 'BARNOOTA',
    register: 'GALMAAʼI',
    signIn: 'SEENI',
    heroTitle: 'Baga Gara Waltajjii Gabaa Itoophiyaa Guddichatti Dhuftan',
    heroSubtitle: 'Meeshaalee addaa argadhu, gatii dhiheessi, fi wantoota hunda irratti elektroniksiitii hanga konkolaataatti walii galtee ajaaʼibaa moʼadhu.',
    searchPlaceholder: 'Gabaa barbaadi...',
    searchButton: 'Barbaadi',
    electronics: 'Elektirooniksii',
    vehicles: 'Konkolaataa',
    jewelry: 'Faaya',
    homeGarden: 'Mana & Iddoo Biqiltuu',
    secureBidding: 'Gatii Dhiheessuu Nageenya Qabu',
    secureBiddingDesc: 'Gatiin kee dhiheessitu nageenya sadarkaa dhaabbataa qabu',
    instantUpdates: 'Fooyya\'iinsa Ariifachiisaa',
    instantUpdatesDesc: 'Sochiiwwan gabaa keetii irratti beeksisa yeroo qabatamaa argadhu',
    bestDeals: 'Walii Galtee Gaarii',
    bestDealsDesc: 'Guyyaa guyyaan meeshaalee gatii guddaa qaban irratti walii galtee ajaaʼibaa argadhu',
    verifiedSellers: 'Gurgurtootaa Mirkaneeffaman',
    verifiedSellersDesc: 'Gurgurtoonni hundi nageenya sammuu keetiitiif mirkaneeffamaniiru',
    email: 'Imeelii',
    password: 'Jecha Icciitii',
    fullName: 'Maqaa Guutuu',
    phoneNumber: 'Lakkoofsa Bilbilaa',
    confirmPassword: 'Jecha Icciitii Mirkaneessi',
    login: 'Seeni',
    createAccount: 'Herrega Uumi',
    forgotPassword: 'Jecha Icciitii Irraanfatte?',
    dontHaveAccount: 'Herrega hin qabdu?',
    alreadyHaveAccount: 'Herrega qabdaa?',
    dashboard: 'Gabatee',
    myBids: 'Gatii Koo Dhiheesse',
    myAuctions: 'Gabaa Koo',
    watchlist: 'Tarree Ilaalchaa',
    messages: 'Ergaawwan',
    settings: 'Qindaa\'ina',
    logout: 'Ba\'i',
    createAuction: 'Gabaa Uumi',
    browseAuctions: 'Gabaa Sakatta\'i',
    currentBid: 'Gatii Ammaa',
    timeLeft: 'Yeroo Hafe',
    placeBid: 'Gatii Dhiheessi',
    buyNow: 'Amma Biti',
    addToWatchlist: 'Gara Tarree Ilaalchaatti Ida\'i',
    bidHistory: 'Seenaa Gatii Dhiheessuu',
    description: 'Ibsa',
    seller: 'Gurgurtaa',
    loading: 'Fe\'aa jira...',
    save: 'Olkaa\'i',
    cancel: 'Dhiisi',
    delete: 'Haqi',
    edit: 'Gulaali',
    view: 'Ilaali',
    language: 'Afaan',
    // About page
    ourMission: 'Ergama Keenya',
    ourStory: 'Seenaa Keenya',
    transparency: 'Ifa Ta\'uu',
    quality: 'Qulqullina',
    community: 'Hawaasa',
    trust: 'Amanamummaa',
    happyUsers: 'Fayyadamtoota Gammadan',
    itemsSold: 'Meeshaalee Gurguraman',
    rating: 'Sadarkaa',
    // Registration and verification
    verifyAccount: 'Herrega Kee Mirkaneessi',
    verificationCodeSent: 'Koodii 6-lakkoofsa gara',
    enterVerificationCode: 'Koodii Mirkaneessaa Galchi',
    verifyingAccount: 'Mirkaneessaa jira...',
    didntReceiveCode: 'Koodii hin arganne?',
    resendOTP: 'OTP Irra Deebi\'ii Ergi',
    sending: 'Ergaa jira...',
    // Subscription
    accountVerified: 'Herregni Mirkaneeffame!',
    activateSubscription: 'Amma maallaqa kaffaltii kee haa kakaasnu',
    selectPaymentMethod: 'Mala Kaffaltii Filadhu',
    payWithTelebirr: 'Telebirr mobile money tiin kaffali',
    payWithChapa: 'Chapa payment gateway tiin kaffali',
    payWithCBEBirr: 'Baankii Daldala Itoophiyaa tiin kaffali',
    processing: 'Adeemsa keessa jira...',
    activateFreeAccount: 'Herrega Bilisaa Kakaasi',
    proceedToPayment: 'Gara Kaffaltii Itti Fufi',
    upgradeAnytime: 'Yeroo kamiyyuu dashboard kee irraa gara karoora kaffaltii fooyya\'uu dandeessa',
    // Auctions
    liveAuctions: 'Gabaa Kallattii',
    browseActiveAuctions: 'Gabaa socho\'aa sakatta\'ii fi gatii kee dhiheessi',
    searchAuctions: 'Gabaa barbaadi...',
    allCategories: 'Ramaddii Hunda',
    endsIn: 'Xumura',
    bids: 'Gatii Dhiheessuu',
    noAuctionsFound: 'Ulaagaa kee wajjin walsimu gabaan hin argamne',
    // Checkout
    checkout: 'Kaffaltii',
    congratulations: 'Baga gammadde! Gabaa kana mo\'atteetta',
    shippingAddress: 'Teessoo Geejjibaa',
    streetAddress: 'Teessoo Daandii',
    city: 'Magaalaa',
    region: 'Naannoo',
    paymentMethod: 'Mala Kaffaltii',
    orderSummary: 'Cuunfaa Ajajaa',
    soldBy: 'Kan gurgure',
    winningBid: 'Gatii Mo\'atee',
    shipping: 'Geejjiba',
    free: 'Bilisaa',
    total: 'Waliigala',
    completePayment: 'Kaffaltii Xumuri',
    paymentSecure: 'Odeeffannoo kaffaltii keetii nageenya qabu fi icciitiin eegame',
    // Auto-bid
    autoBid: 'Gatii-Ofumaa',
    autoBidDescription: 'Sirni hanga hamma guddaa keetii ofumaan siif gatii haa dhiheessu',
    maxAutoBidAmount: 'Hamma gatii-ofumaa guddaa',
    setAutoBid: 'Gatii-Ofumaa Saagi',
    // Create Auction
    createNewAuction: 'Gabaa Haaraa Uumi',
    listYourItem: 'Meeshaa kee tarreessi fi gatii dhiheessuu fudhachuu jalqabi',
    basicInformation: 'Odeeffannoo Bu\'uuraa',
    auctionTitle: 'Mata-duree',
    itemCondition: 'Haala',
    conditionNew: 'Haaraa',
    conditionLikeNew: 'Akka Haaraa',
    conditionGood: 'Gaarii',
    conditionFair: 'Giddugaleessa',
    conditionPoor: 'Dadhabaa',
    pricingSection: 'Gatii Kaa\'uu',
    startingPrice: 'Gatii Jalqabaa',
    reservePrice: 'Gatii Qabamee',
    minimumPriceToSell: 'Gatii xiqqaa gurgurtaaf',
    buyNowPrice: 'Gatii Amma Bituu',
    optionalInstantBuy: 'Gatii bitaa ariifachiisaa filannoo',
    auctionSettings: 'Qindaa\'ina Gabaa',
    auctionDuration: 'Yeroo Gabaa',
    shippingCost: 'Baasii Geejjibaa',
    enterZeroForFree: 'Geejjiba bilisaaf 0 galchi',
    imagesSection: 'Suuraa',
    uploadImages: 'Suuraa Fe\'i',
    uploadUpTo10: 'Hanga suuraa 10 fe\'i. Suuraan jalqabaa suuraa guddaa ta\'a.',
    commissionInfo: 'Komishinii',
    willBeDeducted: 'gatii gurgurtaa dhumaa irraa ni hir\'ata',
    creatingAuction: 'Uumaa jira...',
    // Admin
    adminDashboard: 'Gabatee Bulchaa',
    managePlatform: 'Fayyadamtoota, gabaa bulchi fi sochiiwwan waltajjii hordofi',
    totalUsers: 'Fayyadamtoota Waliigalaa',
    totalActiveAuctions: 'Gabaa Socho\'aa',
    fraudAlerts: 'Akeekkachiisa Gowwoomsaa',
    revenueLabel: 'Galii',
    userManagement: 'Bulchiinsa Fayyadamtootaa',
    searchUsers: 'Fayyadamtoota barbaadi...',
    auctionManagement: 'Bulchiinsa Gabaa',
    searchAuctionsAdmin: 'Gabaa barbaadi...',
    fraudDetectionAlerts: 'Akeekkachiisa Adda Baasuu Gowwoomsaa',
    transactionManagement: 'Bulchiinsa Daldalaa',
    blockUser: 'Cufi',
    viewDetails: 'Ilaali',
    flaggedItem: 'Mallattaa\'e',
    resolveAlert: 'Furmaata Kenni',
    investigateAlert: 'Qoradhu',
    detailsLink: 'Bal\'inaan'
  }
};

export const languages = {
  en: 'English',
  am: 'አማርኛ',
  or: 'Afaan Oromoo'
};

function getTranslation(lang: Language, key: string): string {
  return translations[lang]?.[key as keyof typeof translations['en']] || key;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && ['en', 'am', 'or'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => getTranslation(language, key);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
